### ISSUE TITLE
"Attempt to move beyond end of substream" error when using StreamPump

### ISSUE THREAD

**Issue by andrew92010** [DiscUtils/DiscUtils#142] opened 2019-03-13 08:20 UTC
I use StreamPump to copy a stream to another one, but I sometimes get this error:

System.ArgumentOutOfRangeException: Attempt to move beyond end of substream

When debugging, I see that the exception is fired when setting the position cursor in the Stream.

Can it be a bug of the library? Please reply, because it's a delicate issue that I have to solve.

Let me know. Thanks in advace.

**Comment by LordMike** [comment] 2019-03-13 21:16
Duplicate of #140

**Closed by LordMike** 2019-03-13 21:16 UTC
