### ISSUE TITLE
XFS fileystem V5 fails to enumerate directories with "Substream extends beyond end of parent stream"

### ISSUE THREAD

**Issue by travist13** [DiscUtils/DiscUtils#128] opened 2019-01-30 22:37 UTC
Hi LordMike,

I have been hitting this error when trying to read from any XFS file systems. Specifically, I have seen this on CentOS 7, RedHat 7.5, and SUSE 15. Here is the stack:

![image](https://user-images.githubusercontent.com/13336825/52017664-ea8b3300-249c-11e9-8a00-3d8e3f9d6e1d.png)

Can you help?

Thanks,
Travis

[edit] Added the entry method call to the stack as I missed it on the initial copy.

**Comment by LordMike** [comment] 2019-01-30 22:49
I know very little about XFS and its buildup .. is there any chance you're working on incomplete / corrupt data?

**Comment by zivillian** [comment] 2019-01-30 22:59
This code was written by me - do you have a _small_ image to reproduce?

**Comment by travist13** [comment] 2019-01-30 23:59
The images we get are from Azure. I can login to the VMs just fine and no issues seem to be present. 

Can you get an image from Azure? Here is one that repros the issue:

PublisherName    : OpenLogic
Offer            : CentOS
Skus             : 7.5
Version          : 7.5.20180815

If that doesn't work for you I will try to get a smaller image from CentOS directly.

**Comment by zivillian** [comment] 2019-01-31 15:35
I was able to download an image an reproduce the error. There is indeed a Bug which i've addressed in #129.

Sadly it's stilll not working, because those images use a newer XFS Version which introduced a new Directory Format (dir3) with a new Magic (`XDB3` instead of `XD2B`) and obviously different disk format.

Since i haven't found any specification or documentation regarding this new structure, I'm currently not able to implement it.

**Comment by zivillian** [comment] 2019-01-31 15:36
Google helped: http://ftp.ntu.edu.tw/linux/utils/fs/xfs/docs/xfs_filesystem_structure.pdf, so I may look into this.

**Comment by zivillian** [comment] 2019-01-31 20:51
I've renamed and updated #129 which should now support your image files.

**Closed** 2019-02-05 18:34 UTC

**Comment by travist13** [comment] 2019-02-07 20:09
Just to follow up this fixed the issue on the images I have. Thanks!
